title: POTATOM
email: potatom@potatom.net
description: >-
  Команда разработчиков программного обеспечения. Веб-приложения, сервисы, инфраструктура.
baseurl: ""
url: ""
future: true
permalink: /blog/:title/

collections:
  team:
    output: true
    permalink: /team/:name/
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /articles/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-feed
  - jekyll-seo-tag
