title: POTATOM
email: potatom@potatom.net
description: >-
  Команда разработчиков программного обеспечения. Веб-приложения, сервисы, инфраструктура.
baseurl: ""
url: "https://potatom.ru"
lang: ru_RU
author: POTATOM
future: true
permalink: /blog/:title/

collections:
  team:
    output: true
    permalink: /:name/
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /articles/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - shell.nix

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
