- name: ВЕБ-РАЗРАБОТКА
  description: сайты / веб-приложения

- name: РАЗРАБОТКА ПО
  description: кастомный софт / backend / api

- name: DEVOPS И ИНФРАСТРУКТУРА
  description: linux / docker / ci / мониторинг

- name: КОНСАЛТИНГ
  description: архитектура / code review / аудит

- name: ПОДДЕРЖКА
  description: сопровождение / развитие