- name: ВЕБ-РАЗРАБОТКА
  description: сайты / веб-приложения

- name: РАЗРАБОТКА ПО
  description: софт / backend / api

- name: DEVOPS И ИНФРАСТРУКТУРА
  description: linux / docker / ci / мониторинг

- name: ПОДДЕРЖКА
  description: сопровождение / развитие